### Ordinary transformations
[1]
match='\n'
rewrite='\nif (0==1)\n'

[2]
match='('
rewrite='(!'

[3]
match='=='
rewrite='!='

[4]
match='!='
rewrite='=='

[5]
match='=='
rewrite='<'

[6]
match='<'
rewrite='=='

[7]
match='=='
rewrite='>'

[8]
match='>'
rewrite='=='

[9]
match='='
rewrite='<'

[10]
match='='
rewrite='>'

[11]
match='<'
rewrite='>'

[12]
match='>'
rewrite='<'

[13]
match='++'
rewrite='--'

[14]
match='--'
rewrite='++'

[15]
match='+'
rewrite='-'

[16]
match='+'
rewrite='*'

[17]
match='+'
rewrite='/'

[18]
match='+'
rewrite='%'

[19]
match='*'
rewrite='-'

[20]
match='*'
rewrite='+'

[21]
match='*'
rewrite='/'

[22]
match='*'
rewrite='%'

[23]
match='-'
rewrite='+'

[24]
match='-'
rewrite='*'

[25]
match='-'
rewrite='/'

[26]
match='-'
rewrite='%'

[27]
match='/'
rewrite='-'

[28]
match='/'
rewrite='*'

[29]
match='/'
rewrite='+'

[30]
match='/'
rewrite='%'

[40]
match='%'
rewrite='-'

[41]
match='%'
rewrite='*'

[42]
match='%'
rewrite='/'

[43]
match='%'
rewrite='+'

[44]
match='\n'
rewrite='\nbreak;\n'

[45]
match='\n'
rewrite='\ncontinue;\n'

[46]
match='0'
rewrite='1'

[47]
match='1'
rewrite='0'

[48]
match='if'
rewrite='while'

[49]
match='while'
rewrite='if'

[50]
match='\n'
rewrite='\nwhile(1==1)\n'

[51]
match='&&'
rewrite='||'

[52]
match='||'
rewrite='&&'

[53]
match='!'
rewrite=''


#######################

# Complex transformations

[delete_statement]
match=';:[x];'
rewrite=';'

[delete_statement_after_block]
match='{:[x]}:[y];'
rewrite='{:[x]}'

[delete_block]
match='{:[x]}'
rewrite=''

[delete_block_body]
match='{:[x]}'
rewrite='{}'

[swap_statement]
match=';:[x];:[y];'
rewrite=';:[y];:[x];'

[swap_statement_after_block]
match='{:[x]}:[y];:[z];'
rewrite='{:[x]}:[z];:[y];'

[swap_comma_case_1]
match='(:[x],:[y])'
rewrite='(:[y],:[x])'

[swap_comma_case_2]
match='(:[x],:[y],:[z])'
rewrite='(:[y],:[x],:[z])'

[swap_comma_case_3]
match='(:[w],:[x],:[y],:[z])'
rewrite='(:[w],:[y],:[x],:[z])'

[swap_comma_case_4]
match='(:[x],:[y],:[z])'
rewrite='(:[x],:[z],:[y])'

[delete_line]
match='''
:[x]
'''
rewrite=''

[delete_contiguous_non_whitespace]
match=' :[x] '
rewrite=''

[delete_contiguous_non_whitespace_after_newline]
match='''
:[x] '''
rewrite=''

[delete_contiguous_non_whitespace_after_open_paren]
match='(:[x] :[y])'
rewrite='(:[y])'

[swap_space_delimited]
match=':[x:e] :[y:e]'
rewrite=':[y:e] :[x:e]'

[duplicate_line]
match=':[x\n]'
rewrite=':[x\n]:[x\n]'

# where :[y] would match at some offset.
[duplicate_fragment_inside_braces]
match='{:[x] :[y]}'
rewrite='{:[x] :[y] :[y]}'
