# delete delimited body
[52eb8524fa05]
match='{:[1]}'
rewrite='{}'

[dff77a13461a]
match='(:[1])'
rewrite='()'

[9b5e8aca8c5c]
match='[:[1]]'
rewrite='[]'

# delete delimiters
[6bb28da24e21]
match='{:[1]}'
rewrite=':[1]'

[65ece76caf78]
match='(:[1])'
rewrite=':[1]'

[b2ef7ebf646d]
match='[:[1]]'
rewrite=':[1]'

# duplicate and sequence delimited
[553e2c8cf55c]
match='{:[1]}'
rewrite='{:[1]} {:[1]}'

[2ee939007b89]
match='(:[1])'
rewrite='(:[1]) (:[1])'

[e6665f7b899b]
match='[:[1]]'
rewrite='[:[1]] [:[1]]'

[f1fb9fe38f30]
match='[:[x]]'
rewrite='[:[x]][:[x]]'

# simple block nesting
[10369695c4ae]
match='{:[1]}'
rewrite='{:[1] {:[1]} }'

[da9311f3b2e9]
match='(:[1])'
rewrite='((:[1]) :[1])'

# convert space-separated to tuple
[b8dd83304533]
match=':[x:e] :[y:e]'
rewrite='(:[x], :[y])'

[c4eeeb6120af]
match=':[x:e] :[y:e] :[z:e]'
rewrite='(:[x], :[y])'

[e63befaff2de]
match=':[x:e] :[y:e] :[z:e]'
rewrite='(:[x], :[y], :[z])'

# complex block nesting
[7248731ad60a]
match='{:[1] {:[2]} :[3]}'
rewrite=':[1] {:[1] {:[2]} }:[3]'

[ec96d42ab828]
match='{:[1] {:[2]} :[3]}'
rewrite=':[1] {:[1] {:[2]} :[2]}:[3]'

[8f1128ea8eef]
match='{:[1]{:[2]}:[3]}'
rewrite='{:[1] {:[1] {:[2]} }:[3]}'

[9f00f5d26a37]
match='{:[1]{:[2]}:[3]}'
rewrite='{:[1] {:[1] {:[2]} :[2] }:[3]}'

[ef509e3f7ba5]
match='{:[1]{:[2]}:[3]}'
rewrite='{:[3]}'

[d8adf820a665]
match='{:[1]{:[2]}:[3]}'
rewrite='{:[1] {:[2]} }'

[a7c98dc28868]
match='(:[1](:[2]):[3])'
rewrite='(:[1](:[2]))'

[909f3b9227ed]
match='(:[1](:[2]):[3])'
rewrite='((:[2]))'

[fa5f0c35b0ef]
match='(:[1](:[2]):[3])'
rewrite='((:[2]):[3])'

# swaps
[0b293d897d90]
match=':[1:e], :[2:e]'
rewrite=':[2], :[1]'

# add elements
[e6c866220104]
match='(:[1])'
rewrite='(:[1], :[1])'

# replace code with string data
[5cbf59a5558e]
match=':[x:e]'
rewrite='""'

[0b14387ba986]
match=':[x:e]'
rewrite='unicode"Hello 😃"'

# separate with comma
[84f988aa02cb]
match=':[x:e]'
rewrite=':[x], :[x]'

# change call-like values
[7df98694126d]
match=':[x:e](:[x]())'
rewrite=':[x]()'

[726f80365df6]
match=':[x:e](:[x](:[y], :[y]))'
rewrite=':[x](:[y], :[y])'

[4c53f38fc433]
match=':[x:e](:[1],:[2],:[3])'
rewrite=':[x](:[1], :[3])'

# change things around solidity keywords/syntax
[3ed9feae162e]
match=':[x:e] => :[y:e]'
rewrite=':[y] => :[x]'

[7542f0d30eae]
match='function :[x:e] :[stuff] {:[body]}'
rewrite='modifier mod() {:[body]}'

[dca5bf36a8de]
match=':[x:e] :[stuff] {:[body]}'
rewrite=':[x] :[stuff] payable {:[body]}'

[ec2026617de6]
match=':[x:e] :[stuff] {:[body]}'
rewrite=':[x] :[stuff] payable {}'

[cfb49bc92152]
match='struct :[x:e] {:[body]}'
rewrite='struct :[x]N {:[body]} '

[df23496e5981]
match=':[x:e] is :[y:e]'
rewrite=':[y] is :[x]'

[29e0f512de8a]
match=':[x:e];'
rewrite='using L for :[x]'

[bed10672ab44]
match=':[x:e]{ :[x]{:[rest]}: :[z] :[rest]}'
rewrite=':[x]{:[rest]}'

[ead6e233487b]
match='{ {:[rest]} = :[z]; :[rest] }'
rewrite='{:[rest]}'

[1f67aa432228]
match='(:[x])'
rewrite='returns (:[x])'

[e9448db9c8fc]
match=':[x:e].:[y:e]'
rewrite=':[x]'

[b0f27d95d7af]
match='{:[x]}'
rewrite='unchecked {:[x]}'

[1add02691e66]
match='if (:[x])'
rewrite='if (1)'

[d439dcb6945b]
match='if (([x])if (:[x]))'
rewrite='if (:[x])'

[a72eb25c93ca]
match='if (([x])if ((([x]):[y]) && ([x]):[y])))'
rewrite='if ((([x]):[y]) && ([x]):[y]))'

[801a3830dd84]
match=':[x:e] ? :[x:e] : :[x:e]'
rewrite=':[x]'
